site_name: tremendous-client
site_description: Python client library for the Tremendous API
repo_url: https://github.com/FreshNar/Tremendous-Python
theme:
  name: shadcn
  icon: heroicons:credit-card
  features:
    - content.code.annotate

nav:
  - Home: index.md
  - Getting Started: quick_start.md
  - Reference: reference.md
  - License: license.md
  - Changelog: changelog.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            show_signature: true
          selection:
            members:
              - '!^__init__$' # Exclude __init__ methods

markdown_extensions:
  - codehilite
  - pymdownx.snippets
  - pymdownx.highlight
  - toc:
      permalink: true
