name: ci
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Set up Git
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      # Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Cache pip packages
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: shadcn-mkdocs-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            shadcn-mkdocs-${{ runner.os }}-

      # Install dependencies
      - run: pip install -r requirements.txt

      # Build and deploy MkDocs site
      - run: mkdocs gh-deploy --force
